name: Discord Notification

on:
  push:
    branches:
      - main  # branch name 
  pull_request:
    types: [opened, closed, reopened]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Discord Webhook Action
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: GitHub
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        with:
          args: |
            [{{ EVENT_PAYLOAD.repository.full_name }}:${{ github.ref_name }}] ${{ github.event.commits[0].message }}
            ${{ github.event.commits[0].id }} ${{ github.event.commits[0].message }} - ${{ github.event.commits[0].author.name }}
